### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by amosavian** [LeoNatan/LNPopupController#228] opened 2018-02-14 15:28 UTC
Hi,

I think LNPopupController can't handle right to left layout, This is the result of my test with pseudolanguage mode in XCode

![img_4e0391bc79b5-1](https://user-images.githubusercontent.com/6725192/36212341-ec12e8c8-11b8-11e8-915d-249db1933ea7.jpeg)
![img_5ca835d24871-1](https://user-images.githubusercontent.com/6725192/36212346-eec02ec8-11b8-11e8-93b6-52866a58af5a.jpeg)

**Comment by LeoNatan** [comment] 2018-02-14 17:23
Thanks for reporting!
I will look at this soon.

**Comment by amosavian** [comment] 2018-02-15 07:22
I've added this line to my source to disable RTL and it worked, until there is a real fix. It works on iOS 9+:

```swift
UIView.appearance(whenContainedInInstancesOf: [LNPopupBar.self]).semanticContentAttribute = .forceLeftToRight
```

```objectivec
[[UIView appearanceWhenContainedInInstancesOfClasses:@[[LNPopupBar class]]] setSemanticContentAttribute:UISemanticContentAttributeForceLeftToRight];
```

**Comment by LeoNatan** [comment] 2018-02-15 07:48
Looking at Apple’s implementation, I see an interesting result:
![ce02cc70-1d3d-41e0-952e-f21407273d0b](https://user-images.githubusercontent.com/2270433/36245733-24a03b88-1235-11e8-947c-9522edc4adca.jpeg)

The bar is flipped but the buttons are in the same order. So I need to expose granularity for both and layout accordingly. What should be the defaults?

**Comment by amosavian** [comment] 2018-02-15 08:26
I believe we should do it based on `semanticContentAttribute`. if it's set to `.playback`, then apple's layout should be considered. If it's `.forceLeftToRight` the result must be same as `.playback`. `.forceRightToLeft` must change the order and `.unspecified` must respect UIView's direction.

We can define a separate property for UIBarButton, like `barSemanticContentAttribute`, or simply respects `LNPopupBar.view`'s semantic

**Comment by LeoNatan** [comment] 2018-02-16 15:01
I've implemented this and will release a new version soon.

**Comment by LeoNatan** [comment] 2018-02-16 15:23
Hm, so doing final checks and I found a bug in iOS 11. Setting the `semanticContentAttribute` of a toolbar seems to not affect how it layouts its items. So, if the app is in LTR UI and I use `UISemanticContentAttributeForceRightToLeft`, it breaks the layout.

**Comment by amosavian** [comment] 2018-02-16 15:35
You don't use autolayout as I checked the code.
About toolbar, it uses autolayout on iOS 11 and this can be a bug

**Comment by LeoNatan** [comment] 2018-02-16 16:58
I don't use AutoLayout. I enhanced my layout code to support RTL. Now, the result is funny, all the manual stuff is layout correctly for RTL or LTR according to `semanticContentAttribute` except for the toolbar I use internally. iOS 11 is such a shit release.
Reproduced independently in a demo project and opened a radar.

**Comment by LeoNatan** [comment] 2018-02-16 16:58
I am trying to reverse engineer the toolbar implementation on iOS 11 to make it work correctly.

**Comment by LeoNatan** [comment] 2018-02-17 19:05
I think I found something. Internally, `UIToolbar` now uses a custom `UIStackView` subclass to layout the items. That stack view is not forwarded the toolbar's `semanticContentAttribute`. If I set it manually to `UISemanticContentAttributeForceRightToLeft`, the items are flipped as expected, but the layout is broken.

**Comment by amosavian** [comment] 2018-02-17 21:46
Apple's internal implementations are dirty. I've added a dozen of workarounds to address different iOS bugs.

I suggest you to subclass toolbar and use `[[UIView appearanceWhenContainedInInstancesOfClasses:@[[LNPopupBarToolbar class]]] setSemanticContentAttribute:semantic]`

**Comment by LeoNatan** [comment] 2018-02-17 21:57
Yes! I think I made it work!

**Comment by LeoNatan** [comment] 2018-02-17 21:58
I basically forced Apple's hand and enforced the attribute myself. It now works properly on iOS 10 and 11.

**Comment by LeoNatan** [comment] 2018-02-17 21:59
`semanticContentAttribute` is not marked as `UI_APPEARANCE_SELECTOR` so it cannot be used using the appearance API.

**Comment by amosavian** [comment] 2018-02-17 22:04
It works with UIAppearance in my tests pretty good

**Comment by LeoNatan** [comment] 2018-02-17 22:07
Still, you shouldn't. It works coincidentally due to how the appearance API is implemented, but there is no guarantee it won't break under certain conditions or in a future release.

**Comment by LeoNatan** [comment] 2018-02-17 22:18
I'll push this soon as a minor version to the 2.5.x train. I have not found much time to continue working on the other stuff for 3.0.

**Comment by amosavian** [comment] 2018-02-17 22:19
Thanks a lot.

**Closed** 2018-02-17 22:58 UTC
Labels: enhancement

**Comment by LeoNatan** [comment] 2018-02-17 23:01
Out: https://github.com/LeoNatan/LNPopupController/releases/tag/v2.5.9
Please test and open more issues if you see any RTL problems.

**Comment by RazeeHJ** [comment] 2018-11-06 13:52
I am using RTL, the UIBarButtonItem is positioned correctly however the Title and Subtitle is not, it's just next to the UIBarButtonItem on the right side of it while I want it to be pushed to right side corner of the tab UIBar. How can I solve this?

**Comment by LeoNatan** [comment] 2018-11-06 14:16
Please do not bump closed old issues. Open a new issue with your question. Thank you
