### ISSUE TITLE
Carthage update build failed

### ISSUE THREAD

**Issue by toninospiderman123** [LeoNatan/LNPopupController#478] opened 2021-08-31 12:21 UTC
Hi Leo,

When i try to do carthage update:

*** Fetching LNPopupController
*** Checking out LNPopupController at "2.12.3"
*** xcodebuild output can be found in /var/folders/r_/1kw3z_s11wg83m217n2j_2pc0000gn/T/carthage-xcodebuild.k91369.log
*** Building scheme "LNPopupController" in LNPopupController.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/antonioborgese/Documents/footters-ios-swift/Carthage/Checkouts/LNPopupController/LNPopupController/LNPopupController.xcodeproj -scheme LNPopupController -configuration Release -derivedDataPath /Users/antonioborgese/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5.1_12E507/LNPopupController/2.12.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/r_/1kw3z_s11wg83m217n2j_2pc0000gn/T/LNPopupController SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/antonioborgese/Documents/footters-ios-swift/Carthage/Checkouts/LNPopupController)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/r_/1kw3z_s11wg83m217n2j_2pc0000gn/T/carthage-xcodebuild.k91369.log

**To Reproduce**
1. carthage update

I have the last version of carthage

**Comment by Allan-Nava** [comment] 2021-08-31 12:33
I have the same problem. Any news?

**Comment by toninospiderman123** [comment] 2021-08-31 13:55
OK

[carthage-xcodebuild.k91369.log](https://github.com/LeoNatan/LNPopupController/files/7084460/carthage-xcodebuild.k91369.log)

**Comment by LeoNatan** [comment] 2021-08-31 19:19
In your log, It's trying to compile C++Math.cpp, which doesn't exist anymore. There is no reference to that file. This looks like a bug in Carthage. Not sure what you should do. Probably need to clear the Carthage cache.

**Comment by LeoNatan** [comment] 2021-08-31 19:31
I reproduced this on my Mac. I don't understand why Carthage pull an outdated project.

**Comment by LeoNatan** [comment] 2021-08-31 19:33
Ahhhh, it's because I didn't create a release with the changes. 🤦‍♂️

**Comment by LeoNatan** [comment] 2021-08-31 19:41
Fixed in 2.12.4.

Apologies.

**Closed by LeoNatan** 2021-08-31 19:41 UTC
Labels: bug

**Comment by Allan-Nava** [comment] 2021-09-01 07:39
> Fixed in 2.12.4.
> 
> Apologies.

Thanks for the support!

**Comment by luesp15** [comment] 2023-04-05 08:52
Hi Leo,

with new Xcode Version 14.3 (14E222b) there is again an error when trying to update carthage, here is the error log:

*** Building scheme "LNPopupController" in LNPopupController.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/xx/Documents/xx-ios-swift/Carthage/Checkouts/LNPopupController/LNPopupController/LNPopupController.xcodeproj -scheme LNPopupController -configuration Release -derivedDataPath /Users/xx/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3_14E222b/LNPopupController/2.14.8 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/2y/nkcwmh6x4mx5qw9mg2q3gqcr0000gn/T/LNPopupController SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/xx/Documents/xx-ios-swift/Carthage/Checkouts/LNPopupController)

Carthage version: 0.39.0
