### ISSUE TITLE
Initial full-screen view slides behind status bar; interaction with view element "corrects" the view

### ISSUE THREAD

**Issue by yetdog** [LeoNatan/LNPopupController#179] opened 2017-08-26 17:04 UTC
I have a weird problem that seems to exist no matter what sort of view I have wrapped in the LNPopupController. 

When I initiate the popupbar, it displays properly and as expected. When I tap the bar, it slides up to fill the entire screen; again, as expected. BUT - it seems to slide up too far, behind the status bar. (See pre-tap image). You can see some text behind the Carrier and timestamp in the status bar. Now, when I select an element on the view itself (play/pause button, prev/next, or select another song in the tableview), the view "corrects" and shifts down to the proper alignment. The bottom view (player controls, title/artist) remains in the same coordinates, and everything else stays to the same scale. It just appears that the top area "corrects" and shifts down. I've attached (post-tap) to show the corrected positioning.

I can't for the life of me figure out 1. Why it's misaligning in the first place, and 2. How to reliably correct it. I have implemented a total hack which basically programmatically calls the play/pause button twice, to pause and then resume the audio when the view is expanded to the top. Sometimes this works and aligns the view, sometimes it doesn't. This inconsistency has caused me to reach out and create an issue on this Git site. 

Thank you so much for any insight!

PRE: ![pre-tap](https://user-images.githubusercontent.com/6452866/29743362-48886ff2-8a45-11e7-85b5-044838fe84f2.PNG)

POST: ![post-tap](https://user-images.githubusercontent.com/6452866/29743373-938236c8-8a45-11e7-9cbe-5cceedc924ed.PNG)

**Comment by LeoNatan** [comment] 2017-08-26 17:06
Hello,

This is a strange issue. How do you layout your presented view? Using auto layout? 

Please create a demo project which reproduces this and attach here.

**Comment by LeoNatan** [comment] 2017-09-02 18:17
Ping.

**Comment by Kastet** [comment] 2017-09-08 00:20
Hi @LeoNatan,

I have encountered the same problem. This is very easy to reproduce - add a subview view to a Popup content controller's view using auto layout with the top edge of the subview attached to the Top Layout Guide. However, it fixes itself after rotation. 

<img width="1783" alt="screen shot 2017-09-08 at 10 01 46 am" src="https://user-images.githubusercontent.com/611542/30190623-b4e2ab7a-947e-11e7-811d-3268bab73a13.png">


[Modified LNPopupController-2.3.2 sample](https://github.com/LeoNatan/LNPopupController/files/1286414/LNPopupController-2.3.2.2.zip)

**Comment by LeoNatan** [comment] 2017-09-09 16:57
This is a touch cookie to crack on iOS 11 due to the internal changes of the system. Working on it.

**Comment by yetdog** [comment] 2017-09-10 17:46
Apologies for not responding on this sooner; shortly after posting the issue, my wife and I took a trip to iceland. We're still here, but greatly appreciate you looking into things! Thankful that another user has run into it as well ;)

**Comment by LeoNatan** [comment] 2017-09-16 18:11
I am closing this issue. This will be solved with #183.

**Closed by LeoNatan** 2017-09-16 18:11 UTC
Labels: bug, needs investigation

**Comment by LeoNatan** [comment] 2017-09-17 21:01
Fixed. Please test 2.5.0 release and let me know.
