### ISSUE TITLE
Map example Demo issue

### ISSUE THREAD

**Issue by gu1llaum3** [LeoNatan/LNPopupController#168] opened 2017-06-30 00:12 UTC
Hello,

I tried to launch the demo of the custom popup bar which is related to the map.
It appears that half of the map is blank. I can find where is the problem, actually i didn't try to modify the demo yet. Could you help me please ?

I'm working on Version 8.3.3 on mac OS Sierra 10.12.5.

You can see the attachment for more information :)

Best regards,

Guillaume

![image](https://user-images.githubusercontent.com/28400955/27715701-3cead768-5d39-11e7-88bc-0840e576dab1.png)

**Comment by LeoNatan** [comment] 2017-06-30 05:50
If you move the map around, does the white go away?

I’m don’t have this reproduce on my end.

**Comment by gu1llaum3** [comment] 2017-06-30 08:20
I'm currently just opening it and do not interract with it.
By the way, I tried to implement it with a Google Maps View, it appears perfectly at the bottom and the swipe gesture looks great. But I still have this issue where half of the screen is white. 

I followed this post to integrate the library : https://github.com/LeoNatan/LNPopupController/issues/113#issuecomment-264683130.
Maybe that's why it's not working ?

Thanks again for your help!

**Comment by LeoNatan** [comment] 2017-06-30 10:18
As I’ve explained in the past, CocoaPods is not supported. Please use the documented ways of integration. 

I am not sure this is causing the issue. Please attach the output of `po [[UIWindow keyWindow] recursiveDescription]`.

**Comment by gu1llaum3** [comment] 2017-07-04 21:45
Here is the result of the recursive description : 

```
<COSTouchVisualizerWindow: 0x7fc89de09e30; baseClass = UIWindow; frame = (0 0; 375 667); gestureRecognizers = <NSArray: 0x60800004d0e0>; layer = <UIWindowLayer: 0x60800003e980>>
   | <UILayoutContainerView: 0x7fc89dd08500; frame = (0 0; 375 667); autoresize = W+H; gestureRecognizers = <NSArray: 0x61800004f9f0>; layer = <CALayer: 0x61800003ea60>>
   |    | <UINavigationTransitionView: 0x7fc89dc0bdf0; frame = (0 0; 375 667); clipsToBounds = YES; autoresize = W+H; layer = <CALayer: 0x600000227060>>
   |    |    | <UIViewControllerWrapperView: 0x7fc89df106f0; frame = (0 0; 375 667); autoresize = W+H; layer = <CALayer: 0x6100002363c0>>
   |    |    |    | <UITableView: 0x7fc89f005400; frame = (0 0; 375 667); clipsToBounds = YES; autoresize = W+H; tintColor = UIExtendedSRGBColorSpace 0.913725 0.270588 0.34902 1; gestureRecognizers = <NSArray: 0x60800004efd0>; layer = <CALayer: 0x60800003f7c0>; contentOffset: {0, -64}; contentSize: {375, 533.5}>
   |    |    |    |    | <UITableViewWrapperView: 0x7fc89f016000; frame = (0 0; 375 667); gestureRecognizers = <NSArray: 0x60800004f300>; layer = <CALayer: 0x60800003f8e0>; contentOffset: {0, 0}; contentSize: {375, 667}>
   |    |    |    |    |    | <UITableViewCell: 0x7fc89f026400; frame = (0 459.5; 375 44); text = 'Maps'; clipsToBounds = YES; autoresize = W; layer = <CALayer: 0x60800003eec0>>
   |    |    |    |    |    |    | <UITableViewCellContentView: 0x7fc89de0d560; frame = (0 0; 375 43.5); opaque = NO; gestureRecognizers = <NSArray: 0x60800004de60>; layer = <CALayer: 0x60800003ebc0>>
   |    |    |    |    |    |    |    | <UITableViewLabel: 0x7fc89de0d950; frame = (16 0; 344 43.5); text = 'Maps'; autoresize = RM+BM; layer = <_UILabelLayer: 0x608000088840>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89de0dbf0; frame = (15 43.5; 399 0.5); layer = <CALayer: 0x60800003eca0>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89dc105b0; frame = (0 43.5; 375 0.5); layer = <CALayer: 0x6000002260e0>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89dc10780; frame = (0 0; 375 0.5); layer = <CALayer: 0x600000227600>>
   |    |    |    |    |    | <UITableViewCell: 0x7fc89e045e00; frame = (0 367.5; 375 44); text = 'Apple Music'; clipsToBounds = YES; autoresize = W; layer = <CALayer: 0x600000226520>>
   |    |    |    |    |    |    | <UITableViewCellContentView: 0x7fc89dc0f890; frame = (0 0; 375 43.5); opaque = NO; gestureRecognizers = <NSArray: 0x60800004a2f0>; layer = <CALayer: 0x600000226e20>>
   |    |    |    |    |    |    |    | <UITableViewLabel: 0x7fc89dc0fa40; frame = (16 0; 344 43.5); text = 'Apple Music'; autoresize = RM+BM; layer = <_UILabelLayer: 0x600000087b70>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89de02400; frame = (15 43.5; 399 0.5); layer = <CALayer: 0x60800003eb20>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89dc10080; frame = (0 43.5; 375 0.5); layer = <CALayer: 0x600000228300>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89dc103e0; frame = (0 0; 375 0.5); layer = <CALayer: 0x6000002260a0>>
   |    |    |    |    |    | <UITableViewCell: 0x7fc89f846800; frame = (0 275.5; 375 44); text = 'Split View Controller (Gl...'; clipsToBounds = YES; autoresize = W; layer = <CALayer: 0x610000236020>>
   |    |    |    |    |    |    | <UITableViewCellContentView: 0x7fc89df0fb90; frame = (0 0; 375 43.5); opaque = NO; gestureRecognizers = <NSArray: 0x608000049f00>; layer = <CALayer: 0x610000235f60>>
   |    |    |    |    |    |    |    | <UITableViewLabel: 0x7fc89df0fd40; frame = (16 0; 344 43.5); text = 'Split View Controller (Gl...'; autoresize = RM+BM; layer = <_UILabelLayer: 0x6100000868b0>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89de02230; frame = (15 43.5; 399 0.5); layer = <CALayer: 0x60800003b360>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89dc0feb0; frame = (0 43.5; 375 0.5); layer = <CALayer: 0x600000226d00>>
   |    |    |    |    |    | <UITableViewCell: 0x7fc89f824a00; frame = (0 231.5; 375 44); text = 'Split View Controller (Ma...'; clipsToBounds = YES; autoresize = W; layer = <CALayer: 0x610000235d60>>
   |    |    |    |    |    |    | <UITableViewCellContentView: 0x7fc89df0f400; frame = (0 0; 375 43.5); opaque = NO; gestureRecognizers = <NSArray: 0x61000004c2a0>; layer = <CALayer: 0x610000235da0>>
   |    |    |    |    |    |    |    | <UITableViewLabel: 0x7fc89df0f7a0; frame = (16 0; 344 43.5); text = 'Split View Controller (Ma...'; autoresize = RM+BM; layer = <_UILabelLayer: 0x6100000867c0>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89df0f5b0; frame = (15 43.5; 399 0.5); layer = <CALayer: 0x610000235ec0>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89dc0fce0; frame = (16 43.5; 359 0.5); layer = <CALayer: 0x600000225d20>>
   |    |    |    |    |    | <UITableViewCell: 0x7fc89e02a000; frame = (0 187.5; 375 44); text = 'View Controller'; clipsToBounds = YES; autoresize = W; layer = <CALayer: 0x600000226460>>
   |    |    |    |    |    |    | <UITableViewCellContentView: 0x7fc89dc0f440; frame = (0 0; 375 43.5); opaque = NO; gestureRecognizers = <NSArray: 0x61000004bbe0>; layer = <CALayer: 0x600000227000>>
   |    |    |    |    |    |    |    | <UITableViewLabel: 0x7fc89dc0f5f0; frame = (16 0; 344 43.5); text = 'View Controller'; autoresize = RM+BM; layer = <_UILabelLayer: 0x6000000879e0>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89df0f0e0; frame = (15 43.5; 399 0.5); layer = <CALayer: 0x610000235d20>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89dc0e930; frame = (16 43.5; 359 0.5); layer = <CALayer: 0x600000225e20>>
   |    |    |    |    |    | <UITableViewCell: 0x7fc89e030c00; frame = (0 143.5; 375 44); text = 'Navigation Controller'; clipsToBounds = YES; autoresize = W; layer = <CALayer: 0x600000225920>>
   |    |    |    |    |    |    | <UITableViewCellContentView: 0x7fc89dc0e3e0; frame = (0 0; 375 43.5); opaque = NO; gestureRecognizers = <NSArray: 0x60000004bb80>; layer = <CALayer: 0x600000225b80>>
   |    |    |    |    |    |    |    | <UITableViewLabel: 0x7fc89dc0ee80; frame = (16 0; 344 43.5); text = 'Navigation Controller'; autoresize = RM+BM; layer = <_UILabelLayer: 0x600000086a90>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89dc0f120; frame = (15 43.5; 399 0.5); layer = <CALayer: 0x600000226000>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89dc0e760; frame = (16 43.5; 359 0.5); layer = <CALayer: 0x600000228340>>
   |    |    |    |    |    | <UITableViewCell: 0x7fc89f844a00; frame = (0 99.5; 375 44); text = 'Tab Bar Controller'; clipsToBounds = YES; autoresize = W; layer = <CALayer: 0x610000235c60>>
   |    |    |    |    |    |    | <UITableViewCellContentView: 0x7fc89df0afa0; frame = (0 0; 375 43.5); opaque = NO; gestureRecognizers = <NSArray: 0x60000004ad40>; layer = <CALayer: 0x610000235c80>>
   |    |    |    |    |    |    |    | <UITableViewLabel: 0x7fc89df0ec30; frame = (16 0; 344 43.5); text = 'Tab Bar Controller'; autoresize = RM+BM; layer = <_UILabelLayer: 0x610000086720>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89dc0ec80; frame = (15 43.5; 399 0.5); layer = <CALayer: 0x600000225880>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89dc046d0; frame = (16 43.5; 359 0.5); layer = <CALayer: 0x600000226f20>>
   |    |    |    |    |    | <UITableViewCell: 0x7fc89f016800; frame = (0 55.5; 375 44); text = 'Tab Bar Controller + Navi...'; clipsToBounds = YES; autoresize = W; layer = <CALayer: 0x60800003ba80>>
   |    |    |    |    |    |    | <UITableViewCellContentView: 0x7fc89de01ac0; frame = (0 0; 375 43.5); opaque = NO; gestureRecognizers = <NSArray: 0x61000004a200>; layer = <CALayer: 0x60800003b480>>
   |    |    |    |    |    |    |    | <UITableViewLabel: 0x7fc89de06090; frame = (16 0; 344 43.5); text = 'Tab Bar Controller + Navi...'; autoresize = RM+BM; layer = <_UILabelLayer: 0x6080000863b0>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89df02710; frame = (15 43.5; 399 0.5); layer = <CALayer: 0x61000003c1e0>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89dc05df0; frame = (16 43.5; 359 0.5); layer = <CALayer: 0x6000002277e0>>
   |    |    |    |    |    |    | <_UITableViewCellSeparatorView: 0x7fc89dc0e590; frame = (0 0; 375 0.5); layer = <CALayer: 0x600000226720>>
   |    |    |    |    | <UIImageView: 0x7fc89de11f80; frame = (3 597.5; 369 2.5); alpha = 0; opaque = NO; autoresize = TM; userInteractionEnabled = NO; layer = <CALayer: 0x60800003fd40>>
   |    |    |    |    | <UITableViewHeaderFooterView: 0x7fc89dc10950; frame = (0 0; 375 55.5); text = 'STANDARD SCENES'; autoresize = W; layer = <CALayer: 0x600000226100>>
   |    |    |    |    |    | <_UITableViewHeaderFooterViewBackground: 0x7fc89dc10ba0; frame = (0 0; 375 55.5); autoresize = W+H; layer = <CALayer: 0x600000227840>>
   |    |    |    |    |    | <_UITableViewHeaderFooterContentView: 0x7fc89dc05a40; frame = (0 0; 375 55.5); layer = <CALayer: 0x6000002265a0>>
   |    |    |    |    |    |    | <_UITableViewHeaderFooterViewLabel: 0x7fc89dc10d50; frame = (16 33; 123.5 16); text = 'STANDARD SCENES'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x6000000840b0>>
   |    |    |    |    | <UITableViewHeaderFooterView: 0x7fc89dc10ff0; frame = (0 329.5; 375 38); text = 'DEMO APP'; autoresize = W; layer = <CALayer: 0x600000226560>>
   |    |    |    |    |    | <_UITableViewHeaderFooterViewBackground: 0x7fc89dc113e0; frame = (0 0; 375 38); autoresize = W+H; layer = <CALayer: 0x600000227c20>>
   |    |    |    |    |    | <_UITableViewHeaderFooterContentView: 0x7fc89dc11240; frame = (0 0; 375 38); layer = <CALayer: 0x600000227aa0>>
   |    |    |    |    |    |    | <_UITableViewHeaderFooterViewLabel: 0x7fc89dc11590; frame = (16 15.5; 67 16); text = 'DEMO APP'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x600000087800>>
   |    |    |    |    | <UITableViewHeaderFooterView: 0x7fc89dc11830; frame = (0 421.5; 375 38); text = 'CUSTOM POPUP BAR'; autoresize = W; layer = <CALayer: 0x600000225a60>>
   |    |    |    |    |    | <_UITableViewHeaderFooterViewBackground: 0x7fc89dc11c20; frame = (0 0; 375 38); autoresize = W+H; layer = <CALayer: 0x600000227c80>>
   |    |    |    |    |    | <_UITableViewHeaderFooterContentView: 0x7fc89dc11a80; frame = (0 0; 375 38); layer = <CALayer: 0x600000227e40>>
   |    |    |    |    |    |    | <_UITableViewHeaderFooterViewLabel: 0x7fc89dc11dd0; frame = (16 15.5; 133 16); text = 'CUSTOM POPUP BAR'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x600000087760>>
   |    |    |    |    | <UIImageView: 0x7fc89de12170; frame = (369.5 72.5; 2.5 527.5); alpha = 0; opaque = NO; autoresize = LM; userInteractionEnabled = NO; layer = <CALayer: 0x6080002200e0>>
   |    | <UINavigationBar: 0x7fc89dc07ad0; frame = (0 20; 375 44); opaque = NO; autoresize = W; tintColor = UIExtendedSRGBColorSpace 0.913725 0.270588 0.34902 1; gestureRecognizers = <NSArray: 0x60800004d380>; layer = <CALayer: 0x600000224f20>>
   |    |    | <_UIBarBackground: 0x7fc89de08150; frame = (0 -20; 375 64); userInteractionEnabled = NO; layer = <CALayer: 0x60800003b800>>
   |    |    |    | <UIImageView: 0x7fc89de087a0; frame = (0 64; 375 0.5); userInteractionEnabled = NO; layer = <CALayer: 0x60800003b640>>
   |    |    |    | <UIVisualEffectView: 0x7fc89de08990; frame = (0 0; 375 64); layer = <CALayer: 0x60800003c4c0>>
   |    |    |    |    | <_UIVisualEffectBackdropView: 0x7fc89de09290; frame = (0 0; 375 64); autoresize = W+H; userInteractionEnabled = NO; layer = <UICABackdropLayer: 0x60800003ee00>>
   |    |    |    |    | <_UIVisualEffectFilterView: 0x7fc89dd0b4b0; frame = (0 0; 375 64); autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x61800003ebc0>>
   |    |    | <<UINavigationItemView: 0x7fc89dc09560; frame = (111 8; 153.5 27); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x600000224e80>>: item=<<UINavigationItem: 0x6100001c99c0>: title:'LNPopupController'> title=LNPopupController>
   |    |    |    | <UILabel: 0x7fc89dc09950; frame = (0 3.5; 153.5 21.5); text = 'LNPopupController'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x600000084ab0>>
   |    |    | <UIButton: 0x7fc89de05aa0; frame = (337 11; 22 22); opaque = NO; autoresize = RM+BM; tintColor = UIExtendedSRGBColorSpace 0.913725 0.270588 0.34902 1; layer = <CALayer: 0x60800003bd80>>
   |    |    |    | <UIImageView: 0x7fc89de063b0; frame = (-39 -39; 100 100); alpha = 0; opaque = NO; userInteractionEnabled = NO; tag = 1886548836; layer = <CALayer: 0x60000003d2e0>>
   |    |    |    | <UIImageView: 0x7fc89df0c770; frame = (0 0; 22 22); clipsToBounds = YES; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x610000235480>>
   |    |    | <_UINavigationBarBackIndicatorView: 0x7fc89df0b750; frame = (8 11.5; 13 21); alpha = 0; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x6100002354a0>>
   |    | <UIToolbar: 0x7fc89dd04bc0; frame = (0 667; 375 44); hidden = YES; autoresize = W+TM; layer = <CALayer: 0x61800003d2a0>>
   |    |    | <_UIBarBackground: 0x7fc89dd04fc0; frame = (0 0; 375 44); userInteractionEnabled = NO; layer = <CALayer: 0x61800003b9e0>>
   |    |    |    | <UIImageView: 0x7fc89dd045c0; frame = (0 -0.5; 375 0.5); userInteractionEnabled = NO; layer = <CALayer: 0x61800003ba00>>
   |    |    |    | <UIVisualEffectView: 0x7fc89dd0a9e0; frame = (0 0; 375 44); layer = <CALayer: 0x61800003c680>>
   |    |    |    |    | <_UIVisualEffectBackdropView: 0x7fc89dd03140; frame = (0 0; 375 44); autoresize = W+H; userInteractionEnabled = NO; layer = <UICABackdropLayer: 0x61800003c780>>
   |    |    |    |    | <_UIVisualEffectFilterView: 0x7fc89dd0fe90; frame = (0 0; 375 44); autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x61800003f2a0>>
   |    | <_LNPopupBottomBarSupport: 0x7fc89dd0f8d0; frame = (0 667; 375 0); hidden = YES; userInteractionEnabled = NO; layer = <CALayer: 0x61800003da60>>
```

**Comment by gu1llaum3** [comment] 2017-07-04 21:48
Here is a screenshot ; 
<img width="1168" alt="map" src="https://user-images.githubusercontent.com/28400955/27843385-3926d932-6113-11e7-902f-ec0a2bddab42.png">

**Comment by LeoNatan** [comment] 2017-07-05 17:49
I see no `MKMapView` in that recursive description. Make sure to call this when the map is displayed.

**Comment by gu1llaum3** [comment] 2017-07-06 11:59
I'm sorry Idon't get it, actually the MKMapView is displayed (see the screenshot) so what should I do ?
Could you give me an example please ? 
Thanks :)

**Comment by gu1llaum3** [comment] 2017-07-06 17:45
I wasn't on the map view, you were right. Here is the good recursive description :)

   |    |    |    |    |    |    |    | <GGLOpenGLESLayer: 0x6000000adc20> (layer)
   |    |    |    | <MKAttributionLabel: 0x7f9c7571e1c0; frame = (19 574.26; 28.5566 10.7402); alpha = 0.5; opaque = NO; autoresize = RM+TM; userInteractionEnabled = NO; layer = <CALayer: 0x61000002c6a0>>
   |    |    |    | <MKScaleView: 0x7f9c7540b680; frame = (20 38; 170 20); layer = <CALayer: 0x6080002323a0>>
   |    |    |    |    | <_MKScaleUnitsView: 0x7f9c75721410; frame = (0 -12; 170 20); layer = <CALayer: 0x610000030a20>>
   |    |    |    |    | <_MKLegendString: 0x6100000566e0> (layer)
   |    |    |    |    |    | <_MKLegendString: 0x61000005be70> (layer)
   |    |    |    |    |    | <_MKLegendString: 0x61000005b090> (layer)
   |    |    |    |    |    | <_MKLegendString: 0x610000244830> (layer)
   |    |    |    |    |    | <_MKLegendString: 0x610000244770> (layer)
   |    |    | <UIVisualEffectView: 0x7f9c7554c0b0; frame = (16 60; 33 33); clipsToBounds = YES; opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x6180000319e0>>
   |    |    |    | <_UIVisualEffectBackdropView: 0x7f9c7554cc70; frame = (0 0; 33 33); autoresize = W+H; userInteractionEnabled = NO; layer = <UICABackdropLayer: 0x618000031a60>>
   |    |    |    | <_UIVisualEffectFilterView: 0x7f9c7554ce50; frame = (0 0; 33 33); autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x618000031c60>>
   |    |    |    | <_UIVisualEffectContentView: 0x7f9c7554c400; frame = (0 0; 33 33); clipsToBounds = YES; opaque = NO; autoresize = W+H; layer = <CALayer: 0x61800002f140>>
   |    |    |    |    |    | <UIImageView: 0x7f9c7555bf80; frame = (0 0; 33 33); clipsToBounds = YES; opaque = NO; userInteractionEnabled = N   |    |    | <UIVisualEffectView: 0x7f9c7554d210; frame = (0 0; 375 20); opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x618000031da0>>
   |    |    |    | <_UIVisualEffectBackdropView: 0x7f9c7554d810; frame = (0 0; 375 20); autoresize = W+H; userInteractionEnabled = NO; layer = <UICABackdropLayer: 0x618000031e20>>
   |    |    |    | <_UIVisualEffectFilterView: 0x7f9c7554d9f0; frame = (0 0; 375 20); autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x618000032020>>
   |    |    |    | <_UIVisualEffectContentView: 0x7f9c7554d450; frame = (0 0; 375 20); clipsToBounds = YES; opaque = NO; autoresize = W+H; layer = <CALayer: 0x618000031e00>>
   |    |    |    | <UIVisualEffectView: 0x7f9c77fd4f60; frame = (0 0; 375 0); autoresize = W+H; layer = <CALayer: 0x600000236080>>
   |    |    |    |    | <_UIVisualEffectBackdropView: 0x7f9c77fd77f0; frame = (0 0; 375 0); hidden = YES; autoresize = W+H; userInteractionEnabled = NO; layer = <UICABackdropLayer: 0x600000235dc0>>
   |    |    |    |    | <_UIVisualEffectContentView: 0x7f9c757024d0; frame = (0 0; 375 0); clipsToBounds = YES; autoresize = W+H; layer = <CALayer: 0x610000030aa0>>
   |    |    |    | <UIVisualEffectView: 0x7f9c77fd7220; frame = (0 0; 375 65); autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x60000003a480>>
   |    |    |    |    | <_UIVisualEffectBackdropView: 0x7f9c77fd7460; frame = (0 0; 375 65); autoresize = W+H; userInteractionEnabled = NO; layer = <UICABackdropLayer: 0x60000003a5e0>>
   |    |    |    |    | <_UIVisualEffectFilterView: 0x7f9c77fd7640; frame = (0 0; 375 65); autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x600000235380>>
   |    |    |    |    | <_UIVisualEffectContentView: 0x7f9c77fd88e0; frame = (0 0; 375 65); clipsToBounds = YES; autoresize = W+H; layer = <CALayer: 0x6000002358a0>>
   |    |    |    |    |    |    | <__FakeMarqueeLabel: 0x7f9c7555ee00; baseClass = UILabel; frame = (0 0; 335 65); userInteractionEnabled = NO; layer = <_UILabelLayer: 0x61800008faf0>>
   |    |    |    |    |    |    | <__FakeMarqueeLabel: 0x7f9c7555f600; baseClass = UILabel; frame = (0 0; 335 0); hidden = YES; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x61800008   |    |    |    |    | <_UIBarBackground: 0x7f9c77fd7a00; frame = (0 0; 375 65); userInteractionEnabled = NO; layer = <CALayer: 0x6000002354c0>>
   |    |    |    |    |    | <UIImageView: 0x7f9c77fd7c20; frame = (0 0; 375 65); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x6000002354e0>>
   |    |    |    |    |    | <UIImageView: 0x7f9c77fd7e10; frame = (0 -0.5; 375 0.5); userInteractionEnabled = NO; layer = <CALayer: 0x600000235500>>
   |    |    |    |    | <UIImageView: 0x7f9c77fd8ec0; frame = (0 0; 375 2); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x600000235960>>
  |    |    | <UIImageView: 0x7f9c77fd90b0; frame = (0 0; 0 2); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x6000002359c0>>
   |    |    |    |    | <UIVisualEffectView: 0x7f9c77fd6490; frame = (0 0; 375 65); opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x60000003aac0>>
   |    |    |    |    |    | <_UIVisualEffectBackdropView: 0x7f9c77fd6a00; frame = (0 0; 375 65); autoresize = W+H; userInteractionEnabled = NO; layer = <UICABackdropLayer: 0x60000003ac40>>
   |    |    |    |    |    | <_UIVisualEffectFilterView: 0x7f9c77fd6be0; frame = (0 0; 375 65); autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x600000234fe0>>
   |    |    |    |    |    | <_UIVisualEffectContentView: 0x7f9c77fd66d0; frame = (0 0; 375 65); clipsToBounds = YES; opaque = NO; autoresize = W+H; layer = <CALayer: 0x600   |    |    |    |    |    |    | <LNPopupControllerExample.HigherSearchBar: 0x7f9c7571f480; baseClass = UISearchBar; frame = (0 0; 375 65); text = ''; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x61000005bde0>; layer = <CALayer: 0x610000031100>>
   |    |    |    |    |    |    |    |    | <UISearchBarBackground: 0x7f9c7571ff00; frame = (0 0; 375 65); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x610000030ea0>>
   |    |    |    |    |    |    |    |    |    | <_UIBackdropView: 0x7f9c77fd4870; frame = (0 0; 375 65); hidden = YES; opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <_UIBackdropViewLayer: 0x60000003a840>>
   |    |    |    |    |    |    |    |    |    | <_UISearchBarSearchFieldBackgroundView: 0x7f9c77fd3070; frame = (0 0; 359 35); autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x60000003a540>>
   |    |    |    |    |    |    |    |    |    |    | <_UISearchBarSearchFieldBackgroundView: 0x7f9c77fd3750; frame = (0 0; 359 35); hidden = YES; opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x60000003a420>>
   |    |    |    |    |    |    |    |    |    |    | <_UISearchBarSearchFieldBackgroundView: 0x7f9c77fd4210; frame = (0 0; 359 35); opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x60000003a700>>
   |    |    |    |    |    |    |    |    |    | <UIImageView: 0x7f9c75609570; frame = (74.5 10.5; 13 13); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x60000003a600>>
 189.5 31); text = 'Search for a place or add...'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x600000284b00>>
   |    |    |    | <UIView: 0x7f9c77fdad60; frame = (0 0; 375 65); alpha = 0; autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x6000002361c0>>
   |    |    |    | <UIImageView: 0x7f9c77fd9790; frame = (20 8; 48 48); clipsToBounds = YES; hidden = YES; userInteractionEnabled = NO; layer = <CALayer: 0x6000002362c0>>
   |    |    | <_LNPopupBottomBarSupport: 0x7f9c7550b6b0; frame = (0 667; 375 0); hidden = YES; userInteractionEnabled = NO; layer = <CALayer: 0x618000034340>>

**Comment by LeoNatan** [comment] 2017-07-15 09:35
I am unable to reproduce this issue, and the provided information doesn’t help. The second recursive description is also missing information. I am closing this issue for now.

**Closed by LeoNatan** 2017-07-15 09:35 UTC

**Comment by LeoNatan** [comment] 2017-07-15 11:58
Reproduced on Xcode 9. Investigating, but looks like an Apple bug.
