### ISSUE TITLE
Pop up minimisation requires multiple swipes with scrollable content

### ISSUE THREAD

**Issue by erimfranci** [LeoNatan/LNPopupController#580] opened 2024-09-24 21:51 UTC
### Describe the Bug:

Thank you so much for creating this incredible library!

I recently upgraded from version 2.19.2 to the latest (2.19.7). While I’m glad that some of the iOS 18-related bugs have been addressed, I’ve noticed a bug that's preventing me from upgrading it; When dragging down the pop-up to minimise, it stops midway, requiring multiple swipes to successfully minimise it. This happens consistently every time.

In my setup, I have a UINavigationController within the pop-up and a UIStackView containing several views, making it a long scrollable list. Interestingly, when I remove some views so there’s no scrolling, the issue disappears. This strongly suggests the problem is linked to the presence of scrolling content inside the pop-up.

### Reproduction:

1. Add a scroll view or stackview into the popup that is longer than screen height
2. Pull down the pop up to minimise it
3. It should be stop midway

### Expected Behavior:

It should be minimised without the requirement of second pull down from the user

### Screenshots and/or Videos:

https://github.com/user-attachments/assets/017f5c4c-ccd8-45c7-a263-db0f7fedae44

### Additional Context:

Confirmed same behaviour both on iOS 17 and iOS 18.

**Comment by LeoNatan** [comment] 2024-09-24 22:10
Hi Erim,
Thank you for your kind words. 
could you please create a small example project that reproduces the issue?
In my own demo project I have scrollable content and that works fine. 
Thanks

**Comment by erimfranci** [comment] 2024-09-24 22:43
Thanks for the quick reply! I attached a small example project that reproduces the issue. It might be due to the content but with the example project second pull down is required at the top. If you drag it down not too hard but softly you'll see that it pauses then you need to pull down again. In my project it's a lot more drastic, soft/hard pull doesn't matter it just stops midway. Thanks for looking into it!

https://github.com/user-attachments/assets/10327c65-957b-4994-b642-df21dd63240c

[Test.zip](https://github.com/user-attachments/files/17121895/Test.zip)

**Comment by LeoNatan** [comment] 2024-09-24 22:56
Thanks!
I made some changes not long ago, and probably broke something. Gesture handling is hard. 🤣

**Comment by LeoNatan** [comment] 2024-09-24 22:56
I will take a look soon.

**Comment by erimfranci** [comment] 2024-09-24 22:59
I can only imagine 😆  I guess might be related to #572 as it looks like you fixed this issue on 2.19.3 which introduced the breaking change.

**Comment by LeoNatan** [comment] 2024-09-25 00:44
Please try with 2.19.8. Might have dodged a bullet and it was actually a different bug, rather than gesture handling logic.

**Comment by LeoNatan** [comment] 2024-09-25 00:47
In your original video, I see something akin to a tab bar, but I assume you are faking it with UIToolbar (as you mention it’s a `UINavigationController`)? Because the above fixed bug was only with `UINavigationController`.

**Comment by LeoNatan** [comment] 2024-09-25 00:51
I’m not seeing an issue in your test project that is based on `UITabBarController`. At least for me, it scrolls and dismisses as expected.

**Comment by erimfranci** [comment] 2024-09-25 09:09
Hey! Unfortunately I'm seeing the same issue happening on both test project and my own project with 2.19.8 😞 Any details you need from my side?

My own project also uses a `UITabBarController` it just doesn't have tab titles that's why it looks custom but it's not :)

**Comment by LeoNatan** [comment] 2024-09-25 16:30
Unfortunately, the demo project works as expected for me. If you can, please rejigger it a little to recreate the issue as in the original video. I saw this reproduce in LNPopupUI, and my fix above solved the issue there, for UINavigationController. There might be a similar issue with UITabBarController, but I need a reproduction.

**Comment by erimfranci** [comment] 2024-09-25 19:33
Hi Leo, I think I've got some interesting insights to share with you related to the bug.

I can 100% replicate the bug when `popupInteractionStyle` is set to `.drag`. Both on my own project and test project if I comment this out then everything works fine, although you lose the drag functionality.

I also noticed that when `popupInteractionStyle` is set to `drag` and if you have a pop up where a part of is a static view and a part of it is a scrollview, this bug doesn't happen when you drag down from the static view. It only happens when you drag down from the scroll area (see the video that demonstrates this).

I attached the updated version of the test project for you to see and to reproduce it.

Hope this helps!

https://github.com/user-attachments/assets/b2054a89-46cf-4a55-a655-ad53c5650399

[Test.zip](https://github.com/user-attachments/files/17137621/Test.zip)

**Comment by LeoNatan** [comment] 2024-09-25 21:44
Thanks, I will play with drag interaction to see if I can reproduce. I have to admit I have neglected that interaction style over the years.

**Comment by erimfranci** [comment] 2024-09-25 21:52
Totally understand! To be honest now that I found a way that fixes the
issue, I might get rid of the drag interaction style and move on :) Just
wanted to flag if it helps you in any way!

**Comment by LeoNatan** [comment] 2024-09-26 00:28
Of course, any concrete reproduction helps, so I am grateful. Looking at your most recent video, it looks to me like the drag part works correctly, but the final “finish the transition” portion of the interaction is not invoked over the scroll area. So it is the gesture logic 🫣

**Comment by LeoNatan** [comment] 2024-09-26 03:30
Should be fixed in 2.19.9. Hopefully, nothing else broke as a result of this “fix”. 🤣

**Closed** 2024-09-26 03:29 UTC
Labels: bug

**Comment by LeoNatan** [comment] 2024-09-26 07:05
2.19.10 out with further improvements. I think the system is in a good state right now. The only scenario that is not supported is multidirectional scroll without `isDirectionalLockEnabled = true`, in which case the system gives up and will not attempt to close the popup. I think this is a good compromise, as it is not really clear what is the most desired behavior anyway. And the user can implement the delegate and force one way or another. I also updated the documentation to explicitly state the behavior I want to achieve in all cases.

**Comment by erimfranci** [comment] 2024-09-26 09:14
Just tried on both projects, all issues are fixed now ⭐ Thanks so much Leo, hope you didn't spend too much time on it!

**Comment by LeoNatan** [comment] 2024-09-26 14:35
Cheers
Nah, not too much. And I am much happy now with the result. Less hacky and more sound logic, I think.
