### ISSUE TITLE
iOS 11.2 interaction

### ISSUE THREAD

**Issue by MaticConradi** [LeoNatan/LNPopupController#196] opened 2017-10-31 10:26 UTC
#### Feature request
Include an option for the new animation in the Music app in the latest iOS beta.

**Comment by LeoNatan** [comment] 2017-10-31 12:41
I am running 11.2 beta 1. What is the new animation? Can you provide a short video?

**Comment by MaticConradi** [comment] 2017-10-31 13:06
Animation is interactive. When dismissing, you can drag further down.
[Screen recording](https://drive.google.com/open?id=0BzzZ_pUYYNM7Slc3Tnh4M1VkSUU)

**Comment by LeoNatan** [comment] 2017-10-31 13:33
Oh, didn't even notice it. Not sure if it's not a bug, because it is very buggy at the moment.

If feature, it seems to behave differently when pulled faster or slower. When faster, it opens as in iOS 10, whereas pulling it slowly does this effect.

So part of this is already possible—you can enable drag interaction. Regarding the transition (icon to full album art), it's not new, and I have been thinking how to implement this in a generic way. Theoretically, if I had this mechanism, it could work as expected for drag interaction style.

**Comment by MaticConradi** [comment] 2017-10-31 13:37
It would probably be best to wait until 10.2 GM or public release and see how all turns out.

**Comment by LeoNatan** [comment] 2017-10-31 14:35
Yes indeed.

**Comment by LeoNatan** [comment] 2018-11-09 18:54
Closing in favor of #211

**Closed by LeoNatan** 2018-11-09 18:54 UTC
Labels: enhancement
