### ISSUE TITLE
Custom close button works only first time

### ISSUE THREAD

**Issue by qsdnino** [LeoNatan/LNPopupController#293] opened 2018-10-03 03:58 UTC
As first thanks for this exclusive library. It helps me a lot and makes my new app amaizing.

I have one issue with custom close button on my content view controller.  It is simple button which execute this pece of code

`self.popupPresentationContainer?.closePopup(animated: true, completion: nil)`

Whenever I present presentPopupBar with new instance of content view controller custom close button works only first time.  It close content view controller and my coustom popup bar is visible above UITabBarController which is app root view controller.
After I press in my custom popup bar view controller it restores again popup content view controller as it should.

However it I press againg cusom close button it will not close content view controller anymore.

I hope that this in not bug, maybe I do somethinh wrong. I am using XCode 10 and iPhone XS Max simulator

Thanks!

**Comment by LeoNatan** [comment] 2018-10-03 21:56
Hello,

Sounds like you may not be calling the correct `self.popupPresentationContainer`? Make sure it is the correct instance by setting a breakpoint and inspecting the properties. The `closePopup` method needs to be called for the correct presentation container.

**Comment by qsdnino** [comment] 2018-10-04 12:33
> Hello,
> 
> Sounds like you may not be calling the correct `self.popupPresentationContainer`? Make sure it is the correct instance by setting a breakpoint and inspecting the properties. The `closePopup` method needs to be called for the correct presentation container.

This is not an issue. I made bug myself and that was real issue :)
So I guarantee that this works fine and this is not issue. 
Thanks...

**Comment by LeoNatan** [comment] 2018-11-07 23:21
Sorry, unable to reproduce. The system works as expected. I added the following two methods to `DemoPopupContentViewController` in my example project:

```
- (void)viewDidLoad
{
	[super viewDidLoad];
	
	UIButton* customCloseButton = [UIButton buttonWithType:UIButtonTypeSystem];
	[customCloseButton setTitle:@"Custom Close Button" forState:UIControlStateNormal];
	customCloseButton.translatesAutoresizingMaskIntoConstraints = NO;
	[customCloseButton addTarget:self action:@selector(_closePopup) forControlEvents:UIControlEventTouchUpInside];
	[self.view addSubview:customCloseButton];
	[NSLayoutConstraint activateConstraints:@[
											  [self.view.centerXAnchor constraintEqualToAnchor:customCloseButton.centerXAnchor],
											  [self.view.centerYAnchor constraintEqualToAnchor:customCloseButton.centerYAnchor],
											  ]];
}

- (void)_closePopup
{
	[self.popupPresentationContainerViewController closePopupAnimated:YES completion:nil];
}
```

Closing the popup using the button works as expected.

**Closed by LeoNatan** 2018-11-07 23:21 UTC
Labels: question
