### ISSUE TITLE
Insets are not animated.

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#292] opened 2018-09-24 07:49 UTC
#### Description
While presenting the popup bar, why the insets are not animated when the container is a navigation controller or a view controller?

#### Steps to Reproduce
Your example.

#### Device, OS and Xcode Versions
Simulator, iOS < 11 (10), Xcode 10

**Comment by LeoNatan** [comment] 2018-09-24 08:31
Which insets?

**Comment by iDevelopper** [comment] 2018-09-24 08:40
When you present the popup bar, using navigation controller for example, the bottom inset of the child is not animated i.e. the label "Correct Bottom Layout Guide" move up without animation while the popup bar is showing with animation. The issue is not observed if you present the popup bar with tab bar controller or tab bar controller + navigation controller.

**Comment by LeoNatan** [comment] 2018-09-24 08:44
Right. I did the best I could there. It’s a big mess, especially in the pre-safe area era. I don’t have an answer. 

If it works for iOS 11 and 12, I’m happy.

**Comment by iDevelopper** [comment] 2018-09-24 08:51
What do you mean by pre-safe area?

**Comment by iDevelopper** [comment] 2018-09-24 08:55
Before iOS 11, additional safe area did not exist and I would like to know how the container UITabBarController class does to add one for iOS < 11. Because I also try to use your framework with a custom container controller but with no success!

**Comment by iDevelopper** [comment] 2018-09-24 17:58
Yes I see.
Regarding a custom container view controller, I think that your framework can not work. As you developed the feature, I think you had to test that. Do you have an example?

**Comment by LeoNatan** [comment] 2018-09-24 20:12
Which custom container? Do you mean present a popup from a custom container or present a custom container inside as popup content?

For the former, you have built-in support already using `bottomDockingViewForPopupBar`. For the latter, you will have to explain what the issue is so we can think how to solve.

**Comment by iDevelopper** [comment] 2018-09-25 10:15
Present a popup bar from a custom container. I am trying using bottomDockingViewForPopupBar. When presenting the popup bar from it, the _LNPopupSupportFixInsetsForViewController function fix insets for the container and then the bottom bar move up too.

**Comment by iDevelopper** [comment] 2018-09-25 13:48
Added a demo for custom container in you example. Can I send you by WeTransfer?

**Comment by LeoNatan** [comment] 2018-09-25 16:27
Not familiar with WeTransfer. Perhaps a GitHub repo would be easier?

**Comment by iDevelopper** [comment] 2018-09-25 17:04
Done, https://github.com/iDevelopper/LNPopupControllerExample

**Comment by LeoNatan** [comment] 2018-09-25 17:41
I see the reproduction, but not sure what is going on. I see several issues, but lets focus on the most important one: the bottom bar goes up when presenting the popup bar. Not sure why. I see you are using auto layout, which may be what is causing the issue. Notice the API is frame-oriented, which is a no-no when dealing with autolayout.

My guess is that the bottom bar constraints against the bottom safe area guide is fighting with the framework's update of the safe area (so that content like the label is moved up).

Consider managing your bottom bar manually.

**Comment by iDevelopper** [comment] 2018-09-28 08:51
@LeoNatan , Thanks!

I have updated the repo: https://github.com/iDevelopper/LNPopupControllerExample

If you can have a look when you have time?

**The bottom bar:**
That's it, the bottom bar must not be constrained against the safe area bottom guide but against the superview bottom anchor. I have modified the project to use frame, but we can also use constraints against the container view bottom anchor. But if I use frame, there is an issue with insets for iOS 10 while opening or closing the popup content view. You can set `useConstraintsForBottomBar` to false in containerController to reproduce this issue.

Also, I am surprised that if we do not override `defaultFrameForBottomDockingView` but just `bottomDockingViewForPopupBar`, the popup bar is presenting "full screen"! Why not use in this case the original frame of `bottomDockingViewForPopupBar`? You can comment `defaultFrameForBottomDockingView` function in ContainerController+LNPopupCustomContainer.swift if you want to see the reproduction.

**The child view controller:**
I noticed that if its view constraints are against the superview bottom anchor (the container view), when running on iOS 11 ++, the additional safe area insets does not work. I have to constrain the child view controller view against the bottom safe area guide for iOS 11 ++ and against the container view bottom anchor for iOS 10. Am I missing something or is it right? To reproduce the issue, you can set `useSafeAreaLayoutGuideForChild` to false in containerController.swift.

**insetsForBottomDockingView**:
I don't understand what is it for. Maybe for a bottom bar that would not be at the bottom?

Regards,

**Comment by LeoNatan** [comment] 2018-10-01 11:58
It doesn't make sense to use the current frame, as it may be a different frame every time. `defaultFrameForBottomDockingView` is queried a lot, and should be provided explicitly by the developer. Not implementing that method will result in an undefined behavior, as you are seeing.

`insetsForBottomDockingView` was a workaround for iPhone X. It would inset the bottom docking view and the popup bar as requested. The only inset actually supported is the `bottom`, but the idea was to implement support for `left`, `right` and `top` also, as means to control where on screen the popup bar and popup content appear. I just haven't gotten to implementing this. I don't have a lot of time to work on this framework.

**Comment by iDevelopper** [comment] 2018-10-01 16:49
If `defaultFrameForBottomDockingView ` is not not provided by the developer, I think you should use the original frame, the frame of `bottomDockingViewForPopupBar `. The case when the developer know that the frame never change.

**Comment by LeoNatan** [comment] 2018-11-07 23:14
Looking at the iOS 10 layout code, I will not have to time to look at how to fix this. Going forward, only iOS 11 and above layout will be improved. Closing this issue for now.

**Closed by LeoNatan** 2018-11-07 23:14 UTC
Labels: bug, question
