### ISSUE TITLE
[Enhancement] Shrinking back viewcontroller

### ISSUE THREAD

**Issue by amosavian** [LeoNatan/LNPopupController#230] opened 2018-02-17 21:37 UTC
Hi,

I've noticed Apple Music (and another player which mimics) shrinks back viewcontroller and adds black insets around it. I'm not sure you have time to implement as it's not a needed feature, but it took my curiosity.

Thanks again for this great framework.

![img_f9d3ca3c167d-1](https://user-images.githubusercontent.com/6725192/36345835-d173ccd0-1447-11e8-8706-a2860d351918.jpeg)

**Comment by LeoNatan** [comment] 2018-02-17 22:06
This is a duplicate of #143. 

The challenge is how to implement it generally, which is not easy at all. The last time I was considering this, I thought maybe to have special view controllers which implement this on their own and have this feature only for those controllers. But that is also a lot of work.

**Closed by LeoNatan** 2018-02-17 22:06 UTC
