### ISSUE TITLE
Split view controller issue

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#390] opened 2020-07-31 08:47 UTC
## Description
In your example, when I run it on iPad, iOS 14 with Xcode 12.0 beta 3, split view controller demo is broken. First, I think (for the detail view controller):
```
    if (@available(iOS 14.0, *)) {
        self.preferredSplitBehavior = UISplitViewControllerSplitBehaviorTile;
    }
```

And secondly, and I think it may be an Apple bug, the x origin of the container view frame is -100.

What do you think ?

Thanks.

#### Steps to Reproduce
Run your example

#### Device, OS and Xcode Versions
iOS 14, Xcode 12.0 beta 3, Simulator.

**Comment by LeoNatan** [comment] 2020-07-31 11:06
The origin is like that apparently on purpose. 

https://twitter.com/geoffhackworth/status/1284082382467932163?s=21

What is broken with LNPopupController? The bar starts offscreen?

**Comment by iDevelopper** [comment] 2020-07-31 11:24
Yes it is like Adaptivity app.

In LNPopupController, it is weird! When dragging, the frame of the popuBar is OK. The frame of the navigation controller toolbar is OK. The frame of the rest of popupContentView is x = -100.

Also, there are two popupBars.

<img width="581" alt="screenshot" src="https://user-images.githubusercontent.com/1782450/89030542-faedc980-d330-11ea-9a10-355362b5355a.png">

**Comment by LeoNatan** [comment] 2020-07-31 15:51
I see. The popup bar takes into account the layout margins and safe areas into account. This is a bug in the demo project, not the framework itself. If I layout the internal views to be centered in the safe area, they will be correctly centered.

**Comment by LeoNatan** [comment] 2020-07-31 16:24
Hmm, I do see a problem. Somehow the popup content controller's view doesn't get the correct safe area insets. Will investigate.

**Comment by iDevelopper** [comment] 2020-07-31 16:28
And what about the safe area insets of the primary view controller?

**Comment by iDevelopper** [comment] 2020-07-31 16:36
So, adding the safeAreaInsets.left of the primary view controller to the popup content view origin.x may do the trick, no?

**Comment by LeoNatan** [comment] 2020-07-31 16:37
For the demo project, just enable safe areas in the storyboard. That will fix the "Correct bottom layout guide" label not being centered.

**Comment by iDevelopper** [comment] 2020-07-31 16:38
And reduce the width too.

**Comment by LeoNatan** [comment] 2020-07-31 16:40
Width is controlled by iOS.

**Comment by LeoNatan** [comment] 2020-07-31 18:30
I think it's a bug in iOS 14. I just reproduced the same behavior in an empty project, where adding a sub view doesn't correctly receive the left safe area inset.

**Comment by LeoNatan** [comment] 2020-07-31 19:30
So, if I add a view controller's view without adding it as a child view controller, the safe area is not calculated correctly:

```
TestViewController* rvc = [TestViewController new];
rvc.view.backgroundColor = UIColor.redColor;
rvc.view.frame = self.view.bounds;
//[self addChildViewController:rvc];
[self.view addSubview:rvc.view];
//[rvc didMoveToParentViewController:self];
```

If I do add it as a child view controller, it works as expected. Also, if I add a view that is not attached to a controller, it also correctly sets the safe area insets.

I cannot add the content view controller as a child controller because of bugs in Apple's own controllers. 🤦‍♂️

I have a workaround, but I don't like how it looks when you pull the master controller from the left.

**Comment by LeoNatan** [comment] 2020-07-31 19:36
I've pushed the workaround to Master. I'm not releasing yet, because I want to see if I can make the system work as expected with the safe area layout.

**Comment by iDevelopper** [comment] 2020-07-31 19:38
I will have a look tomorrow. Did you test with the version 3.0 in WIP?

**Comment by LeoNatan** [comment] 2020-07-31 19:40
No, I really don't have time for 3.0; it has not been worked on in a very long time.
I will create 2.9.x with iOS 14 support. I don't know about 3.0.

**Comment by LeoNatan** [comment] 2020-08-01 01:45
Fixed in master.

**Closed by LeoNatan** 2020-08-01 01:45 UTC
Labels: bug

**Comment by iDevelopper** [comment] 2020-08-01 06:39
I had modified like this:
```
- (void)_repositionPopupContentMovingBottomBar:(BOOL)bottomBar
{
	CGFloat percent = [self _percentFromPopupBarForBottomBarDisplacement];
	
	CGFloat barHeight = (_bottomBar.isHidden ? 0 : _bottomBar.bounds.size.height) + _cachedInsets.bottom;
	CGFloat heightForContent = _containerController.view.bounds.size.height - (1.0 - percent) * barHeight;
	
	if(bottomBar)
	{
		CGRect bottomBarFrame = _cachedDefaultFrame;
		bottomBarFrame.origin.y -= _cachedInsets.bottom;
		bottomBarFrame.origin.y += (percent * (bottomBarFrame.size.height + _cachedInsets.bottom));
		_bottomBar.frame = bottomBarFrame;
	}
	
	[self.popupBar layoutIfNeeded];
	[self.popupBar.contentView setAlpha:1.0 - percent];
	
	CGRect contentFrame = _containerController.view.bounds;
	contentFrame.origin.x = self.popupBar.frame.origin.x;
	contentFrame.origin.y = self.popupBar.frame.origin.y + self.popupBar.frame.size.height;
	
	CGFloat fractionalHeight = MAX(heightForContent - (self.popupBar.frame.origin.y + self.popupBar.frame.size.height), 0);
	contentFrame.size.height = ceil(fractionalHeight);
	
	//self.popupContentView.frame = contentFrame;
    CGRect frame = contentFrame;
    UIEdgeInsets insets = UIEdgeInsetsZero;
    if (@available(iOS 11.0, *)) {
        insets = _containerController.view.safeAreaInsets;
    }
    frame.origin.x += insets.left;
    frame.size.width -= (insets.left + insets.right);
    self.popupContentView.frame = frame;
	//_containerController.popupContentViewController.view.frame = _containerController.view.bounds;
    _containerController.popupContentViewController.view.frame = self.popupContentView.bounds;

	[self _repositionPopupCloseButton];
}
```

**Comment by LeoNatan** [comment] 2020-08-02 01:22
That will produce strange results in iPhone on landscape, because the safe area insets are not 0 in that case.

**Comment by iDevelopper** [comment] 2020-08-02 05:53
Exact ! But your implementation is not good either, the labels are not centered:

<img width="879" alt="Capture d’écran 2020-08-02 à 07 52 41" src="https://user-images.githubusercontent.com/1782450/89116520-3903fe00-d495-11ea-88a3-8df47c124ce7.png">

**Comment by iDevelopper** [comment] 2020-08-02 07:03
```
	if(@available(iOS 14.0, *))
	{
		if(_containerController.splitViewController != nil && (_containerController.view.safeAreaInsets.left >= 100 || _containerController.view.safeAreaInsets.right >= 100))
		{
            
			//Take into account RTL
			CGFloat dx = _containerController.view.safeAreaInsets.left >= 100 ? 100 : 0;

			contentFrame.origin.x += dx;
			contentFrame.size.width -= 100;
		}
	}
```

And we need to center the chevron too.

<img width="879" alt="Capture d’écran 2020-08-02 à 08 58 24" src="https://user-images.githubusercontent.com/1782450/89117486-791bae80-d49e-11ea-9728-026a80a0f5b5.png">

**Comment by LeoNatan** [comment] 2020-08-02 12:14
I’m still not finished with the implementation. I’ll look to improve it before release. The second screenshot is what I had in mind when I said “won’t look good”.

**Comment by LeoNatan** [comment] 2020-08-02 18:20
Now it's perfect, I think, or at least I couldn't find problems.

**Comment by iDevelopper** [comment] 2020-08-03 16:28
It looks like it's perfect! Using private APIs. Can you explain?

**Comment by LeoNatan** [comment] 2020-08-03 18:24
It’s not new. This API decides what the safe area insets of each controller should be. Due to a bug, if a controller is not added as a child controller, the safe area insets are calculated to be 0,0,0,0. So in the function I copy the insets of the superview.

**Comment by iDevelopper** [comment] 2020-08-04 15:18
Thanks,

Now I understand how the function decides for the safe area insets of the popup content view controller. However, I don't understand how the popup content view (the one that contains the close button) has the same safe area insets.

**Comment by LeoNatan** [comment] 2020-08-04 16:34
The popup content view is a view with no view controller, so Apple maintains its safe area correctly. But if a view belongs to a controller, it's broken unless the controller is added as a child controller. 😂 What a mess, but what can we do?

**Comment by iDevelopper** [comment] 2020-08-05 16:52
Yes I have the problem when I present (with UIPresentationController, custom) and adding a view to the container view.

**Comment by iDevelopper** [comment] 2020-08-05 16:58
Otherwise with:
```
@implementation SplitViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    
	self.preferredDisplayMode = UISplitViewControllerDisplayModeAllVisible;
    if (@available(iOS 14.0, *)) {
        self.preferredSplitBehavior = UISplitViewControllerSplitBehaviorTile;
    }
}
```

<img width="661" alt="Capture d’écran 2020-08-05 à 18 56 33" src="https://user-images.githubusercontent.com/1782450/89441434-6ed30c00-d74d-11ea-93f3-704f39bdc451.png">

**Comment by iDevelopper** [comment] 2020-08-05 17:06
Why do you have two popupBar in the Split View Controller (Master) example?

<img width="788" alt="Capture d’écran 2020-08-05 à 19 05 00" src="https://user-images.githubusercontent.com/1782450/89442187-ab533780-d74e-11ea-97c0-247ed7fc3f86.png">

What about creating a example for Split View Controller (Detail)?

**Comment by LeoNatan** [comment] 2020-08-07 02:25
The two popup bars are probably a bug somewhere in the demo project. It doesn't really matter, as the example project is just that. I liked the effect of how it looks, so I didn't look into making it work,

**Comment by LeoNatan** [comment] 2020-08-14 19:37
@iDevelopper I made changes to the demo app with regards to split views. Check it out

**Comment by iDevelopper** [comment] 2020-08-19 16:38
Split view controller works pretty well on iPad but many bugs on iPhone...

**Comment by LeoNatan** [comment] 2020-08-19 18:02
I think the bugs are on Apple's side. Even without the popup controller linked, the entire thing is very buggy.
