### ISSUE TITLE
Animate background alpha

### ISSUE THREAD

**Issue by neilgandhi95** [LeoNatan/LNPopupController#277] opened 2018-06-29 04:02 UTC
Much like in the iOS podcast app, is there a way to animate the alpha property behind the view as you drag down? 

Thanks, great library!

**Comment by LeoNatan** [comment] 2018-06-29 15:34
Animations are not possible currently. See #211. Closing this issue as it is a duplicate of that.

**Closed by LeoNatan** 2018-06-29 15:34 UTC
