### ISSUE TITLE
No blur on popupBar

### ISSUE THREAD

**Issue by yarodevuci** [LeoNatan/LNPopupController#111] opened 2016-11-07 02:41 UTC
![simulator screen shot nov 6 2016 6 43 03 pm](https://cloud.githubusercontent.com/assets/13408859/20044817/e33cd3d4-a450-11e6-9a95-6ae45aab209e.png)
On example everything works fine
I did exact thing from example in my current project. However the popupBar appears to be gray. I can change the background color but that is not what I want. I need it to have blur like in example 
Seems like background behind Is black, but why

**Comment by LeoNatan** [comment] 2016-11-07 09:00
I see your navigation bar is not translucent and have colors. Could you please share how you obtain this look? I would like to investigate. How does the bar look like on iOS 9?

**Comment by yarodevuci** [comment] 2016-11-07 09:12
Same problem on IOs 9 and 10.
That is not a navigation bar. That is just a UIView

**Comment by LeoNatan** [comment] 2016-11-07 11:59
Where it says "My Music" is a navigation bar.

**Comment by yarodevuci** [comment] 2016-11-07 18:52
Nope. Really that is a custom view with a dropdown methods. You can check it out in my project

**Comment by yarodevuci** [comment] 2016-11-07 18:54
I had a problems with previous Music Transition pod that didn't work with navigation controller the right way. But i had to delete it because it causes often freezes to UI

**Comment by LeoNatan** [comment] 2016-11-07 18:58
Something is strange here. You are using a blue view instead of a navigation bar and a search bar? Why?

I am not saying the issue with the popup bar is related. Just want to understand. Can you put the project on GitHub? I mean, the project with `LNPopupController` integration? I want to debug it right where you see the problem.

**Comment by yarodevuci** [comment] 2016-11-07 19:00
Search bar is real search bar not a view. I will create a separate branch and let you know. Thank you for support

**Comment by LeoNatan** [comment] 2016-11-07 19:01
Fantastic! Thanks for your willingness to help.

**Comment by LeoNatan** [comment] 2016-11-09 13:31
@yarodevuci Hi
Any news?

**Comment by yarodevuci** [comment] 2016-11-09 17:29
I am working on different project. However I had to delete your plugin because I need album picture for iOS 8 not just for me but other people requested it too..

**Comment by LeoNatan** [comment] 2016-11-10 11:31
You will be able to customize it soon so it is the new look on all OSes.

**Comment by LeoNatan** [comment] 2016-12-02 19:24
Since there is no update, I will close this issue. I cannot reproduce.

**Closed by LeoNatan** 2016-12-02 19:24 UTC
Labels: needs investigation
