### ISSUE TITLE
Custom Popup Bar with transparent background

### ISSUE THREAD

**Issue by degello** [LeoNatan/LNPopupController#294] opened 2018-10-03 21:36 UTC
Hi and thanks for this amazing library,
I've ran into a problem of my own though. I'm wondering if it's possible to make the background color of the minimized view clear instead of just tinting it like in the example. I've tried changing the color in several places but it's only ending up with a completely black background. Look at the image provided to see what i'm trying to achieve. Thanks!

<img width="590" alt="customvc" src="https://user-images.githubusercontent.com/43829798/46440335-54036b00-c763-11e8-9b3d-c35886e65bf1.png">

Something like the minimized youtube player would also be great to achieve, I haven't had any luck by changing the cornerradius (and also using masktobounds of course)
![img_0098](https://user-images.githubusercontent.com/43829798/46440856-fa9c3b80-c764-11e8-9849-bc808a7e8a18.PNG)

**Comment by LeoNatan** [comment] 2018-10-03 21:53
Hello,

Sounds like you want to subclass `LNPopupCustomBarViewController` and implement the view of the custom popup yourself.

**Comment by degello** [comment] 2018-10-03 22:00
I've already done that, I need to add constraints or some type of insets to present the _LNPopupCustomBarViewController_ in the "middle" like the youtube player or just make the _LNPopupCustomBarViewController_ itself transparent and pin a subview inside it to meet my requirements. Let me know if i'm not clear enough.

**Comment by LeoNatan** [comment] 2018-10-03 22:40
So I am not sure what the problem is. Add a view and constrain it to have some padding?

**Comment by qsdnino** [comment] 2018-10-04 02:50
> I've already done that, I need to add constraints or some type of insets to present the _LNPopupCustomBarViewController_ in the "middle" like the youtube player or just make the _LNPopupCustomBarViewController_ itself transparent and pin a subview inside it to meet my requirements. Let me know if i'm not clear enough.

I also have same scenario. Try almost everything and can't make my LNPopupCustomBarViewController subclass transparent.  I present presentPopupBar over UITabBarController which is root view controller for application

**Comment by LeoNatan** [comment] 2018-10-04 08:38
If you set the background color of the LNPopupCustomBarViewController view to transparent, what do you see?

**Comment by qsdnino** [comment] 2018-10-04 12:02
> If you set the background color of the LNPopupCustomBarViewController view to transparent, what do you see?

Yes, sure. I do that in viewDidLoad and set view background to UIColor.clear. Also I set any other subviews views transparent but without any effect.

**Comment by qsdnino** [comment] 2018-10-04 12:28
> What does it look like?

It is white 

Please follow this [link](https://www.dropbox.com/s/advdtgxqcuo411k/Screen%20Shot%202018-10-04%20at%2014.24.56.png?dl=0)

**Comment by LeoNatan** [comment] 2018-10-04 12:39
I don't see how that could be. In my maps example, there is an effect view that blurs the content underneath the popup bar. Your view's background is also white. Could you change it to red just o see if the bar remains white?

**Comment by iDevelopper** [comment] 2018-10-04 12:46
@degello , @qsdnino , @LeoNatan 

Could you have a look at https://github.com/iDevelopper/LNPopupControllerExample ?

I added a custom container controller.

I also added a custom popup bar the Custom Container Demo and replaced the custom popup bar in the Map Scene Demo by one that looks like Youtube bar.

@LeoNatan , I modified LNPopupBar.m too. You should hide the backgroundView view and the shadow view in case of custom popup bar. Or let access to its properties.

There are still some warnings about constraints at runtime in the console but I have not time to investigate.

Hope it helps!

**Comment by qsdnino** [comment] 2018-10-04 13:16
> @degello , @qsdnino , @LeoNatan
> 
> Could you have a look at https://github.com/iDevelopper/LNPopupControllerExample ?
> 
> I added a custom container controller.
> 
> I also added a custom popup bar the Custom Container Demo and replaced the custom popup bar in the Map Scene Demo by one that looks like Youtube bar.
> 
> @LeoNatan , I modified LNPopupBar.m too. You should hide the backgroundView view and the shadow view in case of custom popup bar. Or let access to its properties.
> 
> There are still some warnings about constraints at runtime in the console but I have not time to investigate.
> 
> Hope it helps!

Can't build project. ContainerController.swift is missing

**Comment by iDevelopper** [comment] 2018-10-04 14:47
I don't understand. ContainerController.swift is in the repo and I just downloaded the zip to make a test without any problem!

**Comment by qsdnino** [comment] 2018-10-05 03:07
> I don't understand. ContainerController.swift is in the repo and I just downloaded the zip to make a test without any problem! You have to download the whole repo...

Please check this [link](https://www.dropbox.com/s/8xveufo6ctl331u/Screen-Shot-2018-10-05-at-04.58.10.png?dl=0)
There is explainer screenshot how I open XCode project. Can't run example

**Comment by iDevelopper** [comment] 2018-10-05 04:15
Strange! Is it in the "Demo - Custom Container" folder? If yes, Menu File -> Add Files to "LNPopupControllerExample" and select it.

**Comment by degello** [comment] 2018-10-05 16:58
@iDevelopper thanks a lot! I imported your version of LNPopupController and its now possible to have a transparent background

**Comment by LeoNatan** [comment] 2018-10-05 23:54
Pull requests are welcome.

**Comment by qsdnino** [comment] 2018-10-06 03:16
@iDevelopper I included ContainerController.swift and build project. It works now and the effect is what all of us  need 👍  . However  this is not real UITabBarController implementation. I would be great if we could use UITabBarController for presenting custom bar.

**Comment by iDevelopper** [comment] 2018-10-06 04:08
It works also with a tab bar controller! In MapScene.storyboard, embed the MapViewController in a tab bar controller and test the Map example.

**Comment by LeoNatan** [comment] 2018-10-06 11:57
I’ll take a look.

**Comment by LeoNatan** [comment] 2018-10-08 08:12
Using

```
popupBar.isTranslucent = false
popupBar.backgroundColor = .clear
```

I can already achieve full transparency of the popup bar. There is a small artifact of the hairline, which I am thinking of limiting to translucent bars only.

This is a better solution as it allows custom popup bars to still have the system background, if desired.

**Comment by iDevelopper** [comment] 2018-10-08 09:56
Yes, there remains the problem of the shadow view that we do not necessarily want to keep.

**Comment by qsdnino** [comment] 2018-10-08 11:33
> Using
> 
> ```
> popupBar.isTranslucent = false
> popupBar.backgroundColor = .clear
> ```
> I can already achieve full transparency of the popup bar. There is a small artifact of the hairline, which I am thinking of limiting to translucent bars only.
> 
> This is a better solution as it allows custom popup bars to still have the system background, if desired.

@LeoNatan, @iDevelopper Is possible to hide hairline? I acheive to have transparen custom popup bar, but there is hairline at the top.

**Comment by iDevelopper** [comment] 2018-10-08 11:41
@qsdnino ,

@LeoNatan said:
> There is a small artifact of the hairline, which I am thinking of limiting to translucent bars only.

Waiting for a commit...

**Comment by LeoNatan** [comment] 2018-10-08 18:43
Already committed.

**Closed by LeoNatan** 2018-10-08 18:43 UTC
Labels: question

**Comment by Kedar-27** [comment] 2019-08-20 10:57
@LeoNatan @iDevelopper....how can we acheive full transparent background of popup content view of custombar controller....because, currently it is showing blur view on background...is there any solution

**Comment by Kedar-27** [comment] 2019-08-21 05:25
> @LeoNatan @iDevelopper....how can we achieve full transparent background of popup content view of custombar controller....because, currently, it is showing blur view on background...is there any solution ..in short wanted to achieve full transparency on custombar controller

can somebody please help

**Comment by LeoNatan** [comment] 2019-08-21 05:40
@Kedar-27 Please don't spam threads. This is not your personal support forum and nobody owes you basic usage help.

As I said, read the documentation.

```
popupBar.isTranslucent = false
popupBar.backgroundColor = .clear
```

**Comment by Kedar-27** [comment] 2019-08-21 06:00
> popupBar.isTranslucent = false
> popupBar.backgroundColor = .clear

I read your documentation.....but my problem is with popupcontentview not with popup bar

**Comment by LeoNatan** [comment] 2019-08-21 06:10
I don't think it's possible. If there is transparency in the content controller's view (alpha < 1.0), a blur effect is applied.

**Comment by Kedar-27** [comment] 2019-08-21 06:14
> I don't think it's possible. If there is transparency in the content controller's view (alpha < 1.0), a blur effect is applied.

can we remove that blur effect

**Comment by LeoNatan** [comment] 2019-08-21 06:37
Not at the moment.

**Comment by LeoNatan** [comment] 2019-08-21 06:39
Open a new feature request issue. @Kedar-27
