### ISSUE TITLE
Set myself as popupBarLongPressGestureRecognizerDelegate

### ISSUE THREAD

**Issue by funkenstrahlen** [LeoNatan/LNPopupController#31] opened 2015-12-02 14:23 UTC
How can I set myself as the `popupBarLongPressGestureRecognizerDelegate`?

**Comment by funkenstrahlen** [comment] 2015-12-02 14:43
I tried this:

```swift
        let longpressRecognizer = UILongPressGestureRecognizer(target: self, action: "handleLongPress:")
        longpressRecognizer.delegate = self
        self.popupBar.addGestureRecognizer(longpressRecognizer)
```

But the action did not get called.

**Comment by LeoNatan** [comment] 2015-12-04 16:57
What are you attempting to do? Listen to long press on the bar?

**Comment by funkenstrahlen** [comment] 2015-12-04 17:04
If the popup controller is minified I want to listen to a long press on the whole visible player bar.

**Comment by LeoNatan** [comment] 2015-12-04 17:16
The problem is, the bar already includes a long press gesture recognizer. So with your own recognizer set the delegate and implement the ```gestureRecognizer(_, shouldRecognizeSimultaneouslyWithGestureRecognizer:)``` method. Return ```true``` in this method to allow your recognizer to allow simultaneous recognition.

**Comment by funkenstrahlen** [comment] 2015-12-04 20:38
Thank you for pointing me to the problem with multiple gesture recognizers. This helps a lot.

However I am currently struggling with the first part: Setting the delegate.

`popupBarLongPressGestureRecognizerDelegate` is an attribute of `LNPopupController`. But this is all in the private part of your code, so I can not access it.

What about defining a delegate protocol for the whole lnpopup project, so I can react to certain events and making this a real public api?

**Comment by LeoNatan** [comment] 2015-12-04 20:40
You should not modify the internals of LNPopupController. Instead, add an additional long press gesture recognizer (as you have in the example above), and set that recognizer's delegate.

**Comment by funkenstrahlen** [comment] 2015-12-04 20:47
Ok I did that:

```
    override func viewDidLoad() {
        super.viewDidLoad()
        let longpressRecognizer = UILongPressGestureRecognizer(target: self, action: "handleLongPress:")
        longpressRecognizer.delegate = self
        self.popupBar.addGestureRecognizer(longpressRecognizer)
	}
    
    func handleLongPress(recognizer: UITapGestureRecognizer) {
        print("long press")
    }
    
    func gestureRecognizer(gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWithGestureRecognizer otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        return true
    }
```

However I still do not receive the long press event.

Is that the way you intended to tell me?

**Comment by funkenstrahlen** [comment] 2015-12-04 20:59
Apparently the problem seems to be that `self.popupBar` is not valid.

**Comment by LeoNatan** [comment] 2015-12-04 21:03
Just did the following in the demo project and it worked.

```swift
	func longPress(gestureRecognizer: UILongPressGestureRecognizer) {
		print("Are you talking to me?")
	}
	
	func gestureRecognizer(gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWithGestureRecognizer otherGestureRecognizer: UIGestureRecognizer) -> Bool
	{
		return true
	}
	
	override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
		let popupContentController = storyboard?.instantiateViewControllerWithIdentifier("DemoMusicPlayerController") as! DemoMusicPlayerController
		popupContentController.songTitle = titles[indexPath.row]
		popupContentController.albumTitle = subtitles[indexPath.row]
		
		tabBarController?.presentPopupBarWithContentViewController(popupContentController, animated: true, completion: nil)
		
		let lpgr = UILongPressGestureRecognizer(target: self, action: "longPress:")
		lpgr.delegate = self
		print(tabBarController?.popupBar)
		tabBarController?.popupBar?.addGestureRecognizer(lpgr)
		
		tableView.deselectRowAtIndexPath(indexPath, animated: true)
	}
```

Remember the `popupBar` property is non-nil only after presenting the popup. I did find a bug in the header file, where the `popupBar` is not marked as `nullable` and will push a fix.

**Comment by funkenstrahlen** [comment] 2015-12-04 21:05
I got it working now too!

I tried to configure self.popupBar in viewDidLoad() of popupContentController but popupBar was not valid yet. I did it now in prepareForSegue and it works now.

**Closed** 2015-12-04 21:04 UTC
Labels: question

**Comment by LeoNatan** [comment] 2015-12-04 21:09
👍

Make sure to pull the latest changes. 



Thanks,
Leo Natan

On Dec 4, 2015, at 23:05, Stefan Trauth <notifications@github.com> wrote:

I got it working now too!

I tried to configure self.popupBar in viewDidLoad() of popupContentController but popupBar was not valid yet. I did it now in prepareForSegue and it works now.

**Comment by funkenstrahlen** [comment] 2015-12-04 21:09
Thanks a lot for helping me! :heart:

**Comment by LeoNatan** [comment] 2015-12-04 21:12
Cheers! Happy coding!
